# Generated by Django 5.2 on 2025-04-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="hotel",
            constraint=models.UniqueConstraint(
                fields=("name", "location"), name="name_location"
            ),
        ),
    ]
